### ISSUE TITLE
SSL certificate for the website

### ISSUE THREAD

**Issue by JoraKasapi** [OpenLabsHackerspace/PreservingWB#1]
Is it possible to create a SSL certificate for the website @kominoshja ?

**Comment by kominoshja** [comment]
@JoraKasapi SSL has been active since day 1 :)
https://preservingwb.city/

**Comment by kominoshja** [comment]
Ah, I see what you mean! It seems it was not enforced,  even though it was active. I enforced it. You can close the issue

**Comment by JoraKasapi** [comment]
great , thanks Boris, closing it!
