### ISSUE TITLE
Images on Preservingpristina.city that don't open

### ISSUE THREAD

**Issue by JoraKasapi** [OpenLabsHackerspace/PreservingWB#37]
![Image doesnt open](https://user-images.githubusercontent.com/35333751/102342983-4d571c00-3f9a-11eb-80eb-2a4d07604fb3.PNG)
![Image doesnt open 2](https://user-images.githubusercontent.com/35333751/102343004-534cfd00-3f9a-11eb-8a42-59629c29122f.PNG)
![Image doesnt open 3](https://user-images.githubusercontent.com/35333751/102343022-56e08400-3f9a-11eb-8b9b-ff12f3fbba57.PNG)

These are some of the examples, I think I saw some more. Please can you check it if its a technical problem or we just don't have pics for them?

**Comment by kominoshja** [comment]
@JoraKasapi I fixed the buildings in question, it seems like some images were not downloaded. If you see the broken image mark, it means the photo wasn't downloaded correctly, but if you see just the title, without the broken image icon, that building doesn't have an image

**Comment by JoraKasapi** [comment]
thank you Boris, Great!!
