### ISSUE TITLE
Adding wikimedia commons category link on Preservingpristina.city

### ISSUE THREAD

**Issue by JoraKasapi** [OpenLabsHackerspace/PreservingWB#4]
Here is the main category on Wikimedia commons for Pristina : https://commons.wikimedia.org/wiki/Category:Historic_neglected_buildings_of_Pristina
that we need to add to the preservingpristina.city

**Comment by JoraKasapi** [comment]
I already did this for Pristina but we need to do it in the Kosovo website also, and I didn't know how to do it so I ll need your help here.

**Comment by kominoshja** [comment]
@JoraKasapi Same link for kosovo as for pristina?

**Comment by JoraKasapi** [comment]
yes
