### ISSUE TITLE
Problem on Grand Hotel Pristina when I add the link of wikimedia

### ISSUE THREAD

**Issue by JoraKasapi** [OpenLabsHackerspace/PreservingWB#8]
![gabim](https://user-images.githubusercontent.com/35333751/91053077-9b7a9500-e622-11ea-88e2-eb3dcb261874.JPG)

**Comment by kominoshja** [comment]
@JoraKasapi the comma in the URL makes the platform think you're no longer talking about the link. In these cases, we usually use a URL encoder like https://www.urlencoder.org/  which converts the character from `,` to `%2C`, which the browser understands
